language: python
python:
  - "2.6"
  - "2.7"

install: 
  - "pip install . --use-mirrors"
  - "pip install -r requirements.txt --use-mirrors"
  - "git submodule init"
  - "git submodule update"
script: "python ./tests.py"